version: "2"
plugins:
  rubocop:
    enabled: true
  fixme:
    enabled: true
  reek:
    enabled: true
  markdownlint:
    enabled: true
  flog:
    enabled: true
    config:
      score_threshold: 30.0
checks:
  method-count:
    config:
      threshold: 30
