---
env:
  global:
    - CC_TEST_REPORTER_ID=2d390d3e34f5ebe40f414bbc6532f3c1b550bb8a0327e251382ab0c3b6f2814f
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.3.8
before_install: gem install bundler -v 1.17.1
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec spec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
